name:                dreamgrove-bot
version:             0.1.0.0
github:              "i-r-o-n/dreamgrove-bot"
# license:             
# author:              ""
# maintainer:          ""
# copyright:           ""

extra-source-files:
- readme.md
- changelog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README.md file

dependencies:
- base
- bytestring
- cassava
- discord-haskell
- directory
- hspec
- text
- time
- unliftio
- vector
- yaml 
# - aeson
# - bytestring
# - containers
# - mtl
# - filepath

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  dreamgrove-bot:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dreamgrove-bot

tests:
  dreamgrove-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dreamgrove-bot
